# Generated by Django 3.1.7 on 2021-02-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
