# Generated by Django 3.1.7 on 2021-02-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_case_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='image',
            new_name='mainimage',
        ),
        migrations.RemoveField(
            model_name='case',
            name='axialslices',
        ),
    ]
