# Generated by Django 3.1.2 on 2021-02-10 09:42

from django.db import migrations
import patients.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20210210_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=patients.fields.ShortUUIDField(blank=True, editable=False, max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='slug',
            field=patients.fields.ShortUUIDField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
