# Generated by Django 3.1.7 on 2021-02-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20210223_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='mainimage',
        ),
        migrations.AddField(
            model_name='case',
            name='slices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='ct',
            field=models.FileField(upload_to='files/'),
        ),
    ]
