# Generated by Django 3.1.7 on 2021-02-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20210224_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='slices',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
