# Generated by Django 3.1.7 on 2021-03-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20210225_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='slices',
        ),
    ]
