# Generated by Django 3.1.7 on 2021-03-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_case_slices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='slices',
        ),
    ]
