# Generated by Django 3.1.7 on 2021-03-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_case_slices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='slices',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='img_data/'),
        ),
    ]
