# Generated by Django 3.1.7 on 2021-03-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_auto_20210303_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='slices',
        ),
    ]
