# Generated by Django 3.1.7 on 2021-03-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_remove_case_slices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(editable=False, upload_to='')),
                ('plane', models.IntegerField(choices=[(0, 'axial'), (1, 'sagittal'), (2, 'coronal')], editable=False)),
                ('position', models.PositiveSmallIntegerField(editable=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slice_img', to='patients.case')),
            ],
        ),
    ]
